# Generated by Django 3.0.7 on 2020-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do CLiente')),
                ('payment', models.CharField(max_length=50, verbose_name='Meio de Pagamento')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
